export const homeScreenBg = require('./img/home-screen-bg.jpg')

export const liquidityLogo = require('./img/liquidity-logo.png')
export const liquidityLogoTitle = require('./img/liquidity-logo-title.png')
export const fingerprintIcon = require('./img/fingerprint-icon.png')
export const faceIdIcon = require('./img/face-id.png')
export const pinDeleteIcon = require('./img/pin-delete-icon.png')
export const failPopupIcon = require('./img/fail-popup-icon.png')
export const successPopupIcon = require('./img/success-popup-icon.png')
export const qrScanGuides = require('./img/qr-scan-guides.png')
export const transactionReceiveIcon = require('./img/transaction-receive-icon.png')
export const transactionReceiveSmallIcon = require('./img/transaction-receive-small-icon.png')
export const transactionSendIcon = require('./img/transaction-send-icon.png')
export const transactionSendSmallIcon = require('./img/transaction-send-small-icon.png')
export const transactionExchangeIcon = require('./img/transaction-exchange-icon.png')
export const transactionRejectedIcon = require('./img/transaction-rejected-icon.png')
export const popupBottomEdge = require('./img/popup-bottom-edge.png')

export const sadFaceImage = require('./img/sad-face.png')

export const onboarding1Bg = require('./img/onboarding-1.jpg')
export const onboarding2Bg = require('./img/onboarding-2.jpg')
export const onboarding3Bg = require('./img/onboarding-3.jpg')
export const onboarding4Bg = require('./img/onboarding-4.jpg')
