#!/bin/bash

file="../android/production-keystore.properties"

if [ -f "$file" ]
then
  while IFS='=' read -r key value
  do
    key=$(echo $key | tr '.' '_')
    eval ${key}=\${value}
  done < "$file"
else
  echo "$file not found."
fi

bundletool build-apks \
--bundle=../android/app/build/outputs/bundle/release/app.aab \
--output=../android/app/build/outputs/bundle/release/app.apks \
--mode=universal \
--ks=../android/app/${storeFile} \
--ks-pass=pass:${storePassword} \
--ks-key-alias=${keyAlias} \
--key-pass=pass:${keyPassword}
mv ../android/app/build/outputs/bundle/release/app.apks ../android/app/build/outputs/bundle/release/app.zip
unzip ../android/app/build/outputs/bundle/release/app.zip -d ../android/app/build/outputs/bundle/release/
